Repository open-edge-platform/edge-manageability-framework, pull requests merged in 2025-07, with the labels that each got.

#333 docs: add proposal for simplifying default addon
  design-proposals/cluster-orch-addon.md
Labels: Proposal

#584 Add ingress-route for DM manager
  argocd/applications/configs/infra-external.yaml
  argocd/applications/custom/infra-external.tpl
  argocd/applications/custom/infra-onboarding.tpl
  argocd/applications/templates/infra-external.yaml
  argocd/applications/templates/self-signed-cert.yaml
  mage/generate.go
  pod-configs/module/orch-route53/variable.tf
  terraform/edge-network/variables.tf
Labels: 3.1-CF

#604 Update profile-oxm.yaml to include idv OSprofile
  orch-configs/profiles/profile-oxm.yaml
Labels: 3.1-RC2

#610 Updated infra version to 1.0.20
  argocd/applications/templates/web-ui-infra.yaml
Labels: 3.1-RC2

#614 Infra-external charts release
  argocd/applications/templates/infra-external.yaml
Labels: 3.1-RC2

#616 Update edge node manifest version to latest
  argocd/applications/configs/infra-onboarding.yaml
Labels: 3.1-RC2

#615 Bump github.com/open-edge-platform/infra-managers from 2.14.0 to 2.15.1
  argocd/applications/templates/infra-managers.yaml
Labels: 3.1-RC2
