Repository open-edge-platform/edge-manageability-framework, pull requests merged in 2025-08, with the labels that each got.

#641 Update web-ui-infra version to 1.0.23
  argocd/applications/templates/web-ui-infra.yaml
Labels: 3.1-RC3

#646 Set manual mode to default for OS Resource manager
  orch-configs/clusters/bkc.yaml
  orch-configs/clusters/dev-minimal.yaml
  orch-configs/clusters/dev.yaml
  orch-configs/clusters/onprem-1k.yaml
  orch-configs/clusters/onprem-explicit-proxy.yaml
  orch-configs/clusters/onprem-oxm.yaml
  orch-configs/clusters/onprem.yaml
  orch-configs/profiles/enable-osrm-manual-mode.yaml
  orch-configs/templates/cluster.tpl
Labels: 3.1-RC3

#638 Update edge node manifest version to latest
  argocd/applications/configs/infra-onboarding.yaml
Labels: 3.1-RC3

#653 Update app-orch-tenant-controller
  .test-dependencies.yaml
  argocd/applications/custom/app-orch-tenant-controller.tpl
Labels: 3.1-RC3

#657 Infra-external 2.7.1 release
  argocd/applications/configs/infra-external.yaml
  argocd/applications/configs/infra-onboarding.yaml
  argocd/applications/templates/infra-external.yaml
Labels: 3.1-RC3

#659 Bump osprofile to 0.7.7 with revert VIP cf7 case exclusion
  .github/workflows/virtual-integration.yml
  argocd/applications/configs/infra-managers.yaml
Labels: 3.1-RC3

#663 Updated orch-ui CO release version
  argocd/applications/templates/web-ui-cluster-orch.yaml
Labels: 3.1-RC4

#645 Bump orch-utils chart versions
  argocd/applications/templates/app-deployment-manager-secret.yaml
  argocd/applications/templates/cert-synchronizer.yaml
  argocd/applications/templates/squid-proxy.yaml
  argocd/applications/templates/tenancy-datamodel.yaml
  argocd/applications/templates/tenancy-manager.yaml
  argocd/applications/templates/vertical-pod-autoscaler.yaml
Labels: 3.1-RC4

#667 Infra external release 2.7.2
  argocd/applications/templates/infra-external.yaml
Labels: 3.1-RC4

#672 onprem disable open port
  .tool-versions
  argocd/applications/configs/metallb.yaml
  on-prem-installers/mage/build.go
  on-prem-installers/rke2/rke2installerlocal.sh
Labels: 3.1-RC4

#678 update app-orch-deployment to 2.4.27
  argocd/applications/templates/app-deployment-manager.yaml
Labels: 3.1-RC4

#680 Fix Ubuntu upgrade & cve patches for infra
  argocd/applications/templates/infra-core.yaml
  argocd/applications/templates/infra-onboarding.yaml
Labels: 3.1-RC4

#682 Fix upgrade script
  on-prem-installers/onprem/onprem_upgrade.sh
Labels: 3.1-RC4

#685 Indra-onboarding chart release 1.33.6
  argocd/applications/templates/infra-onboarding.yaml
Labels: 3.1-RC4

#716 Update webui-infra version for release 3.1 branch
  argocd/applications/templates/web-ui-infra.yaml
Labels: 3.1-RC5
