Repository open-edge-platform/edge-manageability-framework, pull requests merged in 2025-05, with the labels that each got.

#241 Bug Fix: Error with exit status 1 during Setup development environment
  .tool-versions
  mage/Magefile.go
Labels: bug, dependencies

#246 ADR for Orchestrator CLI tool
  design-proposals/orch-cli.md
Labels: Proposal

#251 adr: cluster-orch cli
  design-proposals/co-cli.md
Labels: Proposal

#359 Remove python dependency
  .tool-versions
Labels: build

#250 design: Scale provisioning of EMT-S nodes
  design-proposals/emts-scale-provisioning.md
  design-proposals/images/eim-emt-s-scale-internet-access.png
  design-proposals/images/eim-pxe-network-topology.png
Labels: Proposal

#361 Fix typos in the various markdown files.
  README.md
  argocd-internal/root-app/templates/root-app.yaml
  argocd/root-app/templates/root-app.yaml
  design-proposals/README.md
  design-proposals/app-orch-deploy-applications.md
  design-proposals/app-orch-dp-import.md
  design-proposals/app-orch-helm-to-dp.md
  design-proposals/co-cli.md
  design-proposals/orch-cli.md
  e2e-tests/installer/README.md
  e2e-tests/installer/auto_install.py
  e2e-tests/orchestrator/orchestrator_test.go
  mage/Magefile.go
  mage/deploy.go
  mage/registry.go
  mage/router.go
  mage/utils.go
  on-prem-installers/cmd/onprem-orch-installer/generate_fqdn
  on-prem-installers/onprem/onprem_backup_restore.sh
  on-prem-installers/onprem/upgrade_postgres.sh
  orch-configs/profiles/enable-metrics.yaml
  orch-configs/profiles/enable-tracing.yaml
  pod-configs/buckets/README.md
  pod-configs/module/application-load-balancer/variable.tf
  pod-configs/module/aurora/variable.tf
  pod-configs/module/cloudwatch-log-group/variable.tf
  pod-configs/module/orch-route53/variable.tf
  pod-configs/orchestrator/cluster/variable.tf
  pod-configs/orchestrator/orch-route53/variable.tf
  pod-configs/orchestrator/vpc/variable.tf
  pod-configs/utils/aurora/reset-db-password.sh
  pod-configs/utils/config-provision.sh
  pod-configs/utils/lib/common.sh
  pod-configs/utils/provision.sh
  pod-configs/utils/provisioning/package.sh
  pod-configs/utils/tools/aurora-snapshot-backup-restore.sh
  terraform/orchestrator/terraform.tfvars
  tools/profiles-coverage.sh
  tools/render-apps-all-clusters.sh
Labels: documentation

#290 docs(design): improve orchestrator deployment experience
  design-proposals/deploy-experience-improvement.md
  design-proposals/deploy-experience-improvement.svg
Labels: Proposal

#370 Adding approvers for design proposals
  .github/CODEOWNERS
Labels: repo-maintenance

#312 feat: upgrade ArgoCD to 3.0.0
  installer/Makefile
  mage/Magefile.go
  on-prem-installers/mage/build.go
Labels: upgrade

#374 feat(config): introduce EN proxy settings
  new-installer/cmd/config/form.go
  new-installer/cmd/config/form_test.go
  new-installer/cmd/config/orch_config.go
  new-installer/cmd/config/validate.go
  new-installer/cmd/config/validate_test.go
  new-installer/internal/config/config.go
Labels: FEATURE, installer

#386 add proxy settings to app-orch-catalog
  argocd/applications/custom/app-orch-catalog.tpl
  argocd/applications/templates/app-deployment-manager.yaml
  argocd/applications/templates/app-orch-catalog.yaml
Labels: enhancement
